### ISSUE TITLE
Créer des variables

### ISSUE THREAD

**Issue by Annsca** [Fouloscopie/robotique#6]
I'd really like to send you some code for this as I've got ideas I'd really like to try out. However I'm really struggling because of the fact I can't add attributes at the class level as this would require changing the main class. I'm finding it impossible to do any of my ideas because I can't have variables that keep their value every time the method is called as I have to initialise them inside the method. I've tried using global or persistent variables but those create other problems. Every time I think of a solution, it doesn't work because I need a non-global, non-persistent variable which doesn't get reset everytime the function is called. I feel like there is probably an easy solution to my problem which I am missing. Can anyone help?

J'aimerais vraiment t'envoyer mon program pour ta vidéo vu que j'ai des idées que j'ai vraiment envie d'essayer. Mais j'ai un problème qui m'en empeche. Je n'arrive pas à rajouter des nouvelles variables qui garde leur valeur à chaque fois que la fonction (update) est appelée(?). Puisque je ne peux pas initialiser au niveau de la classe entière vu que je devrais changer le main pour faire ça, il faut que j'initialise les variables a l'interieur de la fonction et du coup, à chaque fois que la fonction est rappelée, les valeurs sont réinitialisées. J'ai éssayer d'utiliser des variables globales ou persistent mais ca cause d'autres problemes. A chaque fois que je pense à une solution ca ne marche pas parce que il me faudrait une variable non-globale, non-persistente mais qui ne se réinitialise pas à chaque fois. J'imagine qu'il doit y avoir une solution simple à mon probleme mais je ne la trouve pas. Est ce que qui que se soit peut m'aider?

(Posté en français parce que c'est la langue qu'on parle mais aussi en anglais parce que j'ai appris la progra en anglais alors du coup j'utilise probablement les mauvais termes en francais et du coup c'est peut etre pas clair. Vous pouvez répondre en français ou en anglais, comme vous voulez les deux me vont :) ) 

Merci!!!  (Thanks!!!)

**Comment by viannou** [comment]
Au niveau des propriétés du robot (au même endroit que id, x, y, orientation, vx, vy, ...,) tu peux ajouter tes propres variables, et même initialiser leur valeur avec le signe =.
Au niveau de la fonction Robot(), tu peux aussi initialiser les valeurs.
Ces variables sont persistantes, mais indépendantes d'un robot à l'autre.

**Comment by Annsca** [comment]
Merci beaucoup pour ta réponse viannou :) Heureusement j'ai remarqué hier que je racontais n'importe quoi x) J'etais persuadé qu'il fallait passer toutes les valeurs de robot à main pour qu'elles marchent.
